export const TAG_LIST: string[] = [
  'dp',
  'graphs',
  'greedy',
  'binary search',
  'math',
  'data structures',
  'constructive algorithms',
  'brute force',
  'implementation',
  'sortings',
  'number theory',
  'strings',
  'dfs and similar',
  'trees',
  'combinatorics',
  'bitmasks',
  'two pointers',
  'dsu',
  'shortest paths',
  'flows',
  'games',
  'geometry',
  'hashing',
  'probabilities',
  'string suffix structures',
  'matrices',
  'fft',
  'ternary search',
  'expression parsing',
  'meet-in-the-middle',
  '2-sat',
  'chinese remainder theorem',
  'convex hull',
  'schedules',
  'divide and conquer',
  'interactive',
  'graph matchings',
  'segment tree',
];
